home44/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('webauth.urls')),
    path('', include('webapp.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path
from webapp.views import FoodDetailView, OrderDetailView, OrderCreateView, FoodCreateView, OrderUpdateView, \
    OrderFoodCreateView, FoodUpdateView, FoodDeleteView, OrderFoodDeleteView, OrdersListView, FoodListView, \
    OrderCourierUpdateView, OrdersCourierListView, InitialView, OrderFoodAjaxCreateView,OrderFoodAjaxUpdateView

app_name = 'webapp'

urlpatterns = [
    path('', OrdersListView.as_view(), name='orders_list'),
    path('login/', InitialView.as_view(), name='initial_view'),
    path('courier/orders/', OrdersCourierListView.as_view(), name='orders_courier_list'),
    path('food/', FoodListView.as_view(), name='food_list'),
    path('food/<int:pk>', FoodDetailView.as_view(), name='food_detail'),
    path('food/create', FoodCreateView.as_view(), name='food_create'),
    path('food/<int:pk>/edit', FoodUpdateView.as_view(), name='food_edit'),
    path('food/<int:pk>/delete', FoodDeleteView.as_view(), name='food_delete'),
    path('order/<int:pk>', OrderDetailView.as_view(), name='order_detail'),
    path('order/create', OrderCreateView.as_view(), name='order_create'),
    path('order/<int:pk>/update', OrderUpdateView.as_view(), name='order_update'),
    path('order/<int:pk>/courier_update', OrderCourierUpdateView.as_view(), name='order_courier_update'),
    path('order/<int:pk>/food/create', OrderFoodAjaxCreateView.as_view(), name='order_food_create'),
    path('order/<int:pk>/food/delete', OrderFoodDeleteView.as_view(), name='order_food_delete'),
    path('order/food/<int:pk>/update', OrderFoodAjaxUpdateView.as_view(), name='order_food_update'),
]

webauth/urls.py
from django.urls import path
from webauth.views import DeliveryLoginView
from django.contrib.auth.views import LogoutView



app_name = 'webauth'

urlpatterns = [
    path('login/', DeliveryLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

webapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT, related_name='employee', verbose_name='Пользователь')
    phone = models.CharField(max_length=50, verbose_name='Телефон')

    def __str__(self):
        return self.user.get_full_name()
    class Meta:
        permissions = [
            ('is_courier', 'Разрешения курьера'),
            ('is_operator', 'Разрешения оператора')
        ]


class Food(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название')
    description = models.TextField(max_length=1000, null=True, blank=True, verbose_name='Описание')
    photo = models.ImageField(verbose_name='Фотография')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Цена')

    def __str__(self):
        return self.name


class Order(models.Model):
    STATUS_NEW = 0
    STATUS_PREPARING = 1
    STATUS_ON_WAY = 2
    STATUS_DELIVERED = 3
    STATUS_CANCELED = 4

    STATUS_CHOICES = (
        (STATUS_NEW, 'Новый'),
        (STATUS_PREPARING, 'Готовится'),
        (STATUS_ON_WAY, 'В пути'),
        (STATUS_DELIVERED, 'Доставлен'),
        (STATUS_CANCELED, 'Отменён')
    )

    contact_phone = models.CharField(max_length=50, verbose_name='Контактный телефон')
    contact_name = models.CharField(max_length=100, verbose_name='Имя клиента')
    delivery_address = models.CharField(max_length=200, null=True, blank=True, verbose_name='Адрес доставки')
    status = models.IntegerField(default=STATUS_NEW, verbose_name='Статус', choices=STATUS_CHOICES)
    operator = models.ForeignKey(User, null=True, blank=True, related_name='orders', verbose_name='Оператор',
                                 on_delete=models.PROTECT)
    courier = models.ForeignKey(User, null=True, blank=True, related_name='delivered', verbose_name='Курьер',
                                on_delete=models.PROTECT)

    def __str__(self):
        return self.contact_phone


class OrderFood(models.Model):
    order = models.ForeignKey(Order, related_name='foods', verbose_name='Заказ', on_delete=models.PROTECT)
    food = models.ForeignKey(Food, related_name='+', verbose_name='Блюдо', on_delete=models.PROTECT)
    amount = models.IntegerField(verbose_name='Количество')

    def __str__(self):
        return str(self.food)

webapp/forms.py
from django import forms
from webapp.models import Food, Order, OrderFood


class FoodForm(forms.ModelForm):
    class Meta:
        model = Food
        exclude = []


class OrderForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['status'].choices = [Order.STATUS_CHOICES[Order.STATUS_NEW],
                                         Order.STATUS_CHOICES[Order.STATUS_PREPARING],
                                         Order.STATUS_CHOICES[Order.STATUS_CANCELED], ]

    class Meta:
        model = Order
        exclude = ['courier', 'operator']


class OrderCourierForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['status'].choices = [Order.STATUS_CHOICES[Order.STATUS_DELIVERED],
                                         Order.STATUS_CHOICES[Order.STATUS_ON_WAY] ]

    class Meta:
        model = Order
        fields = ['status', 'courier']


class OrderFoodForm(forms.ModelForm):
    class Meta:
        model = OrderFood
        exclude = ['order']

webapp/views.py
from django.views.generic import DetailView, CreateView, UpdateView, View, DeleteView, ListView, FormView
from django.urls import reverse
from django.http import HttpResponseRedirect, JsonResponse
from webapp.models import Food, Order, OrderFood
from webapp.forms import FoodForm, OrderForm, OrderFoodForm, OrderCourierForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q
from django.shortcuts import get_object_or_404


class InitialView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if 'couriers' in request.user.groups.values_list('name', flat=True):
            return HttpResponseRedirect(reverse('webapp:orders_courier_list'))
        else:
            return HttpResponseRedirect(reverse('webapp:orders_list'))


class FoodListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Food
    template_name = 'food_list.html'
    permission_required = 'webapp.view_food'


class FoodCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Food
    template_name = 'food_create.html'
    form_class = FoodForm
    permission_required = 'webapp.add_food'

    def get_success_url(self):
        return reverse('webapp:food_detail', kwargs={'pk': self.object.pk})


class FoodUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Food
    template_name = 'food_edit.html'
    form_class = FoodForm
    permission_required = 'webapp.change_food'

    def get_success_url(self):
        return reverse('webapp:food_detail', kwargs={'pk': self.object.pk})


class FoodDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Food
    template_name = 'food_delete.html'
    permission_required = 'webapp.delete_food'

    def get_success_url(self):
        return reverse('webapp:food_list', kwargs={})


class FoodDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Food
    template_name = 'food_detail.html'
    permission_required = 'webapp.view_food'


class OrdersListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Order
    template_name = 'index.html'
    permission_required = 'webapp.is_operator'


class OrdersCourierListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Order
    template_name = 'index.html'
    permission_required = 'webapp.is_courier'

    def get_queryset(self):
        queryset = Order.objects.filter(Q(status=Order.STATUS_PREPARING) | Q(status=Order.STATUS_ON_WAY))
        return queryset


class OrderDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView, FormView):
    model = Order
    template_name = 'order_detail.html'
    permission_required = 'webapp.view_order'
    form_class = OrderFoodForm


class OrderUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Order
    template_name = 'order_update.html'
    form_class = OrderForm
    permission_required = 'webapp.change_order'

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.pk})


class OrderCourierUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Order
    template_name = 'order_update.html'
    fields = []
    permission_required = 'webapp.is_courier'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['link'] = 'Взять заказ' if self.object.status == Order.STATUS_PREPARING else 'Завершить заказ'
        context['if_own_order'] = self.object.courier == self.request.user
        return context

    def form_valid(self, form):
        self.object.courier = self.request.user

        if self.object.status == Order.STATUS_PREPARING:
            self.object.status = Order.STATUS_ON_WAY
        elif self.object.status == Order.STATUS_ON_WAY:
            self.object.status = Order.STATUS_DELIVERED
        else:
            return super().form_invalid(self.form)

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.pk})


# Представления для создания заказа
class OrderCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Order
    template_name = 'order_create.html'
    form_class = OrderForm
    permission_required = 'webapp.add_order'

    def form_valid(self, form):
        form.instance.operator = self.request.user
        if form.instance.status != Order.STATUS_NEW:
            return self.form_invalid(form)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.pk})


# ... и для добавления блюд в заказ
class OrderFoodCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = OrderFood
    form_class = OrderFoodForm
    template_name = 'order_food_create.html'
    permission_required = 'webapp.add_order'

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.order.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order_pk'] = self.kwargs.get('pk')
        return context

    def form_valid(self, form):
        form.instance.order = Order.objects.get(pk=self.kwargs.get('pk'))
        return super().form_valid(form)


class OrderFoodAjaxCreateView(CreateView):
    model = OrderFood
    form_class = OrderFoodForm

    def form_valid(self, form):
        order = get_object_or_404(Order, pk=self.kwargs.get('pk'))
        form.instance.order = order
        order_food = form.save()
        return JsonResponse({
            'food_name': order_food.food.name,
            'amount': order_food.amount,
            'order_pk': order_food.order.pk,
            'food_pk': order_food.food.pk,
            'pk': order_food.pk,
            'edit_url': reverse('webapp:order_food_update', kwargs={'pk': order_food.pk}),
        })

    def form_invalid(self, form):
        return JsonResponse({
            'errors': form.errors
        }, status='422')


class OrderFoodAjaxUpdateView(UpdateView):
    model = OrderFood
    form_class = OrderFoodForm
    print('In OrderFoodAjaxUpdateView')
    def form_valid(self, form):
        order_food = form.save()
        return JsonResponse({
            'food_name': order_food.food.name,
            'food_pk': order_food.food.pk,
            'amount': order_food.amount,
            'pk': order_food.pk
        })

    def form_invalid(self, form):
        return JsonResponse({
            'errors': form.errors
        }, status='422')


class OrderFoodDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = OrderFood
    template_name = 'order_food_delete.html'
    permission_required = 'webapp.delete_food'

    def post(self, request, *args, **kwargs):
        if request.POST.get('delete') == 'no':
            url = self.get_success_url()
            return HttpResponseRedirect(url)
        else:
            return super(OrderFoodDeleteView, self).post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.order.pk})

webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    {% block styles %}{% endblock %}
</head>
<body>

{% block menu %}
    <nav class="navbar navbar-expand-sm navbar-light bg-light mb-5">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                    aria-controls="navbarNavAltMarkup" aria-expanded="true" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse  pl-0" id="navbarNavAltMarkup">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="  nav-link " href="
                                {% if perms.webapp.is_operator %}{% url 'webapp:orders_list' %}
                                {% elif perms.webapp.is_courier %}{% url 'webapp:orders_courier_list' %}
                                {% endif %}">Список заказов </a>
                    </li>
                    {% if perms.webapp.is_operator %}
                        <li class="nav-item active">
                            <a class="nav-link " href="{% url 'webapp:food_list' %}">Список блюд</a>
                        </li>
                    {% endif %}

                </ul>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item active">
                            <p class=" nav-link  text-secondary "> Добро пожаловать, {{ user.username }}</p>

                        </li>
                        <a class="  nav-link " href="{% url 'webauth:logout' %}">Выйти</a>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock menu %}
<div class="container">
    {% block content %}{% endblock %}
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

webapp/templates/food_create.html
{% extends 'base.html' %}
{% block title %}Добавить блюдо{% endblock %}
{% block content %}
    <form action="{% url 'webapp:food_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock %}

webapp/templates/food_delete.html
{% extends 'base.html' %}


{% block title %}Удалить блюдо{% endblock title %}

{% block content %}

    <form action="{% url "webapp:food_delete" food.pk %}" method="post">
        {% csrf_token %}

        <h2>Вы действительно хотите удалить блюдо {{ food.name }}?</h2>

        <div>
            <input class="btn btn-link"
                   type="button" value="Отменить"
                   onclick="window.history.go(-1);"/>
            <input class="btn btn-link" type="submit" value="Подтвердить"/>
        </div>
        <br>

    </form>

{% endblock content %}

webapp/templates/food_detail.html
{% extends 'base.html' %}
{% block title %}Блюдо{% endblock %}
{% block content %}
    <div class="col-sm-6 pl-0">
        <div class="card ">
            <div class="card-header p-0">
                <a class=" nav-item nav-link active d-inline-block float-right " href="{% url 'webapp:food_edit' food.pk %}"><i
                        class="fas fa-user-edit"></i></a>
                <a class="nav-item nav-link active d-inline-block float-right" href="{% url 'webapp:food_delete' food.pk %}"><i
                        class="fas fa-user-times"></i></a>
            </div>
            <div class="card-body">
                <h3>{{ food.name }}</h3>
                <p>{{ food.description }}</p>
                <img class="float-left card-img-top " src="{{ food.photo.url }}" alt="Картинка еды">
                <h6 class="mt-3">Цена: {{ food.price }} с.</h6>
            </div>
        </div>
    </div>

{% endblock %}

{# Откройте /food/<pk>, чтобы посмотреть картинку еды на этой странице #}

webapp/templates/food_edit.html
{% extends 'base.html' %}
{% block title %}Редактировать блюдо{% endblock %}
{% block content %}
    <form action="{% url 'webapp:food_edit' food.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock %}

webapp/templates/food_list.html
{% extends 'base.html' %}


<title>{% block title %}    Список заказов {% endblock title %}</title>

{% block content %}
    <table>
        <h3>Список блюд</h3>
        <a href="{% url 'webapp:food_create' %}">Добавить блюдо</a>
        <thead>
        <tr>

            <th>Наименование блюда</th>
            <th>Цена</th>
            <th>Просмотр</th>
        </tr>
        </thead>

        {% for food in object_list %}
            <tr>
                <td>{{ food.name }}</td>
                <td>{{ food.price }}</td>
                <td><a href="{% url 'webapp:food_detail'  food.pk %}">📜</td>
            </tr>
            </tr>
        {% endfor %}
    </table>
{% endblock content %}

webapp/templates/index.html
{% extends 'base.html' %}


<title>{% block title %}    Список заказов {% endblock title %}</title>

{% block content %}
    <table>
        <h3>Список заказов</h3>
        {% if perms.webapp.is_operator %}
            <a href="{% url 'webapp:order_create' %}">Создать заказ</a>
        {% endif %}
        <thead>
        <tr>

            <th>Номер заказа</th>
            <th>Статус заказа</th>
            <th>Просмотр</th>
        </tr>
        </thead>

        {% for order in object_list %}
            <tr>
                <td>{{ order.pk }}</td>
                <td>{{ order.get_status_display }}</td>
                <td><a href="{% if perms.webapp.is_operator %}{% url 'webapp:order_detail'  order.pk %}
                            {% elif perms.webapp.is_courier %}{% url 'webapp:order_courier_update'  order.pk %}
                            {% endif %}">📜</td>
            </tr>
            </tr>
        {% endfor %}
    </table>
{% endblock content %}

webapp/templates/order_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Добавить заказ{% endblock %}

{% block content %}
    <form action="{% url 'webapp:order_create' %}" method="post">
        {% csrf_token %}
        {{ formset.media }}
        {{ form.as_p }}
        {{ request.messages }}
        {% for form in formset %}
            <hr>
            <div class="ml-5">
                {{ form.as_p }}
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock %}

webapp/templates/order_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Заказ{% endblock %}
{% block content %}
    <h3>Заказ №{{ order.pk }}</h3>
    {% if perms.webapp.is_operator %}
        <a href="{% url 'webapp:order_update' order.pk %}">Изменить заказ</a><br>
    {% elif perms.webapp.is_courier %}
        <a href="{% url 'webapp:order_courier_update' order.pk %}"></a><br><br>
    {% endif %}
    <h5>Данные заказа:</h5>
    <p>Контактный телефон: {{ order.contact_phone }}</p>
    <p>Имя: {{ order.contact_name }}</p>
    <p>Адрес доставки: {{ order.delivery_address }}</p>
    <p>Статус заказа: {{ order.get_status_display }}</p>
    <p>Оператор: {{ order.operator }}</p>
    <p>Курьер: {{ order.courier }}</p>
    <h5>Заказанные блюда:</h5>
    <div id="food_list">
        {% for order_food in order.foods.all %}


            <p id="order_food_{{ order_food.pk }}">Блюдо: <span id="order_food_name_{{ order_food.pk }}"
                                                                data-food_pk="{{ order_food.food.pk }}">{{ order_food.food.name }}</span>,
                <span id="order_food_amount_{{ order_food.pk }}">{{ order_food.amount }}</span> шт.
                <a href="{% url 'webapp:order_food_update'  order_food.pk %}" class="edit_link"
                   data-pk="{{ order_food.pk }}"><i class=" fas fa-user-edit"></i>
                </a>
                <a href="{% url 'webapp:order_food_delete'  order_food.pk %}" class="fas fa-user-times"></a></p>
            </p>
        {% endfor %}
    </div>
    <button type="button" id="order_food_add">Добавить блюда</button>


    <div class="modal" id='food-add-dialog' tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="text-danger" id="food_form_errors"></div>
                    <form id="food_form" action="{% url 'webapp:order_food_create' order.pk %}" method="post"
                          onsubmit="return false">
                        {% csrf_token %}
                        {{ form.as_p }}

                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" id="food_submit">Save changes</button>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

{% block scripts %}
    <script type="application/javascript" src="{% static 'js/main.js' %}">


    </script>
{% endblock scripts %}

webapp/templates/order_detail_page.html
{% load staticfiles %}
<h5>Данные заказа:</h5>
<p>Контактный телефон: {{ order.contact_phone }}</p>
<p>Имя: {{ order.contact_name }}</p>
<p>Адрес доставки: {{ order.delivery_address }}</p>
<p>Статус заказа: {{ order.get_status_display }}</p>
<p>Оператор: {{ order.operator }}</p>
<p>Курьер: {{ order.courier }}</p>
<h5>Заказанные блюда:</h5>
<div id="food_list">
    {% for order_food in order.foods.all %}
        {#        <p>Блюдо: {{ order_food.food.name }}, {{ order_food.amount }} шт.#}
        {#            <a href="{% url 'webapp:order_food_update'  order_food.pk %}">#}
        {#                <i class="fas fa-user-edit"></i></a>#}
        {#            <a href="{% url 'webapp:order_food_delete'  order_food.pk %}"><i#}
        {#                    class="fas fa-user-times"></i></a></p>#}

        <p>Блюдо: <span id="'order_food_name_{{ order_food.pk }}" data-food_pk="{{ order_food.food.pk }}">{{ order_food.food.name }}</span>,
            <span id="order_food_amount_{{ order_food.pk }}">{{ order_food.amount }}</span> шт.
            <a href="{% url 'webapp:order_food_update'  order_food.pk %}" class="edit_link fas fa-user-edit" data-pk="{{ order_food.pk }}">
                </a>
            <a href="{% url 'webapp:order_food_delete'  order_food.pk %}" class="fas fa-user-times"></a></p>
        </p>
    {% endfor %}
</div>
<script type="application/javascript" src="{% static 'js/main.js' %}"></script>

webapp/templates/order_food_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Добавить заказ{% endblock %}

{% block content %}
    {# Не выводить форму, если статус связанного заказа "Доставлен" или "Доставляется" #}
    {% if order.status == 'delivered' or order.status == 'on_way' %}
        <h2>Заказ уже доставляется или доставлен</h2>
    {% else %}
        <form action="{% url 'webapp:order_food_create' order_pk %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    {% endif %}
{% endblock %}

webapp/templates/order_food_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Удалить блюдо из заказа{% endblock %}

{% block content %}

    {% if order.status == 'delivered' or order.status == 'on_way' %}
        <h2>Заказ уже доставляется или доставлен</h2>
    {% else %}
        <form action="{% url "webapp:order_food_delete" orderfood.pk %}" method="post">
            {% csrf_token %}

            <h2>Вы действительно хотите удалить блюдо "{{ orderfood.food.name }}"?</h2>

            <div>
                <input class="btn btn-link"
                       type="button" value="Отменить"
                       onclick="window.history.go(-1);"/>
                <input class="btn btn-link" type="submit" value="Подтвердить"/>
            </div>
            <br>

        </form>
    {% endif %}
{% endblock content %}

webapp/templates/order_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Изменить заказ{% endblock %}

{% block content %}

    {% if perms.webapp.is_courier %}
        <form action="{% url 'webapp:order_courier_update' order.pk %}" method="post">
        {% csrf_token %}
        {% include 'order_detail_page.html' %}
        <br>
        {% if order.get_status_display == 'Готовится' %}
            <button type="submit" class="btn btn-primary">Взять заказ</button>
        {% elif if_own_order and order.get_status_display == 'В пути' %}
            <button type="submit" class="btn btn-primary">Завершить заказ</button>
        {% endif %}

    {% elif perms.webapp.is_operator %}
        {% if order.get_status_display == "Доставлен" or order.get_status_display == 'В пути' %}
            <h2>Заказ уже доставляется или доставлен</h2>
        {% else %}
            <form action="{% url 'webapp:order_update' order.pk %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}



            <button type="submit" class="btn btn-primary">Сохранить</button>
        {% endif %}

    </form>
    {% endif %}
{% endblock %}