home44/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('webauth.urls')),
    path('', include('webapp.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webauth/urls.py
from django.urls import path
from webauth.views import DeliveryLoginView
from django.contrib.auth.views import LogoutView



app_name = 'webauth'

urlpatterns = [
    path('login/', DeliveryLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

webauth/models.py
from django.db import models

# Create your models here.

webauth/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
# Create your views here.

class DeliveryLoginView(LoginView):
    template_name = 'login.html'

webauth/templates/login.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <title>Вход</title>
</head>
<body>
<div class="container">
    <h1 class="text-center">Вход</h1>
    <form action="{% url 'webauth:login' %}" method="post">
        {% csrf_token %}
        {% if has_error %}
            <p class="form-text text-danger text-center">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="form-row form-group">
            <label for="username" class="col-2 form-text">Имя пользователя:</label>
            <input type="text" class="form-control col-10" name="username" id="username">
        </div>
        <div class="form-row form-group">
            <label for="password" class="col-2 form-text">Пароль:</label>
            <input type="password" class="form-control col-10" name="password" id="password">
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Войти</button>
        </div>
    </form>
</div>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>